### ISSUE TITLE
Incorporate Con-PCA in the COOL

### ISSUE THREAD

**Issue by dav3r** [cisagov/cool-system#82]
- [x] Break out [cisagov/cool-accounts/provisionaccount-role-tf-module](https://github.com/cisagov/cool-accounts/tree/develop/provisionaccount-role-tf-module) into its own repo [Done: see [`cisagov/provisionaccount-role-tf-module`](https://github.com/cisagov/provisionaccount-role-tf-module)]
- [x] Create AWS accounts via ControlTower
  - [x] "PCA (Staging)"
  - [x] "PCA (Production)"
- [x] Provision AWS accounts via new [cisagov/cool-accounts-pca](https://github.com/cisagov/cool-accounts-pca) repo
  - [x] Staging
  - [x] Production
- [x] Provision COOL IAM accounts (in Users account) in [cisagov/cool-users-pca](https://github.com/cisagov/cool-users-pca) for
  - [x] Barry H.
  - [x] Zachary W.
  - [x] Their CI/CD account (ghactions-pca)
- [x] Provision COOL IAM group for PCA Terraformers in Users account (in  [cisagov/cool-users-pca](https://github.com/cisagov/cool-users-pca))
- [ ] ~~Inject cisagov Docker Hub credentials into their GitHub account secrets.~~
  - [ ] ~~[cisagov/con-pca-cicd](https://github.com/cisagov/con-pca-cicd)~~
- [x] Create single role & policy in [cisagov/cool-accounts/terraform](https://github.com/cisagov/cool-accounts/tree/develop/terraform) that allows terraforming staging and production PCA AWS accounts (only) - see https://github.com/cisagov/cool-accounts/pull/68 and [`cisagov/cool-pca-transitgateway-attachment`](https://github.com/cisagov/cool-pca-transitgateway-attachment)
- [x] Transit Gateway
  - [x] assign them CIDR blocks for production and staging environments
  - [x] add to their production deployment
  - [x] add to their staging deployment
  - [x] add to [cisagov/cool-sharedservices-networking](https://github.com/cisagov/cool-sharedservices-networking) repo - done in https://github.com/cisagov/cool-sharedservices-networking/pull/35
- [x] Route 53
  - [x] Create necessary public records in [cisagov/cool-dns-cyber.dhs.gov](https://github.com/cisagov/cool-dns-cyber.dhs.gov) - done in https://github.com/cisagov/cool-dns-cyber.dhs.gov/pull/35
  - [x] Associate PCA VPC with private DNS zone in Shared Services - done in https://github.com/cisagov/cool-pca-transitgateway-attachment/commit/af42c13e4f642cf718a3880a65ec34816af1f605
  - [x] Allow creation of records in private DNS zone in Shared Services - done in https://github.com/cisagov/cool-sharedservices-networking/pull/35 and https://github.com/cisagov/cool-users-pca/pull/4
- [x] Simple Email Service (SES)
  - [x] Change [cisagov/cool-dns-cyber.dhs.gov/sessendemail_role.tf](https://github.com/cisagov/cool-dns-cyber.dhs.gov/blob/develop/sessendemail_role.tf#L15-L19) to allow PCA AWS accounts to send email - done in https://github.com/cisagov/cool-dns-cyber.dhs.gov/pull/32
- [x] Teach INL guys how to use:
  - [x] terraform workspaces
  - [x] AWS_SHARED_CREDENTIALS_FILE environment variable
  - [ ] Possibly AWS_PROFILE as well

**Comment by teal-e** [comment]
Con-PCA project goal is to have this incorporation completed by Nov 16, 2020

**Comment by zenine07** [comment]
@dav3r  As per our discussion - here are the aws resources that the Github Actions account would need access to. This should be enough to get started, but there might be some small ones that sneak in that would need added.

acm
autoscaling
cloudwatch
cloudwatch-alarms
cloudwatch-logs
cognito
iam
lambda
load balancing v2
ecs
rds
route53
s3
ses
sns
sqs
sts - assume role
systems manager - parameter store

**Comment by teal-e** [comment]
@zenine07 can you please review this check list again and, to the best of your knowledge, confirm it's wholly representative of everything the dev team needs to do before we (INL +kelly) can do what's needed to get the pilot in gear? As in, once dev checks off everything on this list by Jan 8th,  we (INL + kelly) will be able to do the alpha/pre-pilot testing the week of Jan 11th and then by Jan 20th kick off the pilot?

**Comment by zenine07** [comment]
@teal-e Had a conversation with @dav3r today and the check list looks representative of everything the dev team needs to accomplish. At the moment, the main items that need accomplished still are the transit gateway, route53 and SES. The Docker Hub credentials are lower priority. Depending on how all of that goes, the 8th sounds like a reasonable timeline.

Also, this is just for con-pca. There is a separate ticket open for the account for domain-manager incorporation into the COOL. #114

**Comment by dav3r** [comment]
Note that [`cisagov/cool-pca-transitgateway-attachment`](https://github.com/cisagov/cool-pca-transitgateway-attachment) was written and deployed to create the resources required in order to apply the Terraform code in [`cisagov/con-pca-cicd`](https://github.com/cisagov/con-pca-cicd).

**Comment by dav3r** [comment]
I believe all work is completed for this issue.  If additional work is required, please open a new issue.
