### ISSUE TITLE
Replace ServerSetup script functionality with GoPhish composition

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cool-system#90]
# 🚀 Feature Proposal #

The [`serversetup.sh` script](https://github.com/noahpowers/ServerSetup/blob/master/serversetup.sh) is currently used by the assessment folks to perform manual configuration of teamservers _after_ they have been deployed.  The portions of this script that are being used should instead be ported to [Ansible](https://www.ansible.com/) and [cloud-init](https://cloud-init.io/).

The portions of the `serversetup.sh` script that can be applied when the AMI is being built should be ported to Ansible, while those portions that can only be applied at deployment time (such as those involving instance-specific data) should be ported to cloud-init.

## Motivation ##

There are several reasons why it is advantageous to port the modifications from `serversetup.sh` to Ansible and cloud-init:

* When the assessors tell us that a teamserver is misbehaving (e.g. see https://github.com/cisagov/cool-system/issues/81), we currently have no way of knowing _a priori_ if this is due to an error in the AMI build process or an error that was made when manually running `serversetup.sh`.  This complicates and lengthens our debugging process.  By porting the modifications from `serversetup.sh` to Ansible and cloud-init, we would _know_ that the teamserver instance was in a working state when handed over to the assessors.
* Porting the modifications from `serversetup.sh` to Ansible and cloud-init would reduce the burden on the assessors, since they would no longer need to perform the manual configuration process.
* Porting the modifications from `serversetup.sh` to Ansible and cloud-init removes manual steps and therefore makes the teamserver instance production process more reproducible and less prone to error.

Note that this work is related to https://github.com/cisagov/cool-system/issues/138.

## Tasks ##
TODO: Make GitHub issues for each item below that doesn't have one.

[`cisagov/cool-assessment-terraform`](https://github.com/cisagov/cool-assessment-terraform):
- [x] https://github.com/cisagov/cool-assessment-terraform/issues/110: Make email-sending domain a Terraform variable and make Postfix container use it (cloud-init)
- [x] https://github.com/cisagov/cool-assessment-terraform/issues/111: Allow Teamserver instances to talk to port 587 (Postfix container's published SMTP mail submission port) on Gophish instances

[`cisagov/pca-gophish-composition-packer`](https://github.com/cisagov/pca-gophish-composition-packer):
- [x] https://github.com/cisagov/pca-gophish-composition-packer/issues/35: Replace [default postfix users and credentials](https://github.com/cisagov/pca-gophish-composition/blob/develop/secrets/postfix/users.txt) with customized creds
- [x] https://github.com/cisagov/pca-gophish-composition-packer/issues/36: Disable and remove `exim4` (Mail Transfer Agent) service - it conflicts with the mail-submission port we want postfix to use
- [x] https://github.com/cisagov/pca-gophish-composition-packer/issues/37: Modify `docker-compose.yml` so that Postfix service publishes ports 25, 587, and 993 to the Gophish host
- [x] https://github.com/cisagov/pca-gophish-composition-packer/issues/38: Install Thunderbird and `dnsutils` - these will be useful for assessors

Not needed for minimum viable product, but definitely want later:
* Pull Postfix username/password from SSM prior to container startup (e.g. via cloud-init)
* Automate DNS record creation (A, MX, TXT (DKIM, SPF, DMARC)); talk to [Domain Manager](https://github.com/cisagov/domain-manager-api) team about this
* Sort out Mailhog/Postfix certificate trust issues so that Mailhog can "release" emails to be sent via Postfix

## Acceptance criteria ##

- [x] A freshly-deployed assessment environment can be used to send emails for the following types of assessments, as confirmed by a representative from each:
  - [x] RVA - Specific acceptance criteria  (provided by @justinforbes):
    - [x] Mail server configured with proper TLS certs and domain information populated to enable sending emails to third parties - see https://github.com/cisagov/cool-assessment-terraform/issues/115
    - [x] Mail server configured to allow emails from Cobalt Strike Team Server
    - [x] Mail server configured to receive emails from Internet
    - [x] Postfix users can be added by assessment operators without regenerating DKIM key - see https://github.com/cisagov/pca-gophish-composition-packer/issues/46
    - [x] [Webmail](https://github.com/noahpowers/ServerSetup/blob/master/serversetup.sh#L1065) installed to view emails OR Thunderbird set up to easily add and autoconfigure user accounts - see https://github.com/cisagov/cool-assessment-terraform/issues/124
    - [x] Team Server has valid TLS cert and two Cobalt Strike C2 profiles that use it (replicate [`httpsc2doneright()` function from `ServerSetup.sh`](https://github.com/noahpowers/ServerSetup/blob/master/serversetup.sh#L587-L633)) - see https://github.com/cisagov/cool-assessment-terraform/issues/116
  - [x] RPT - Specific acceptance criteria (provided by @sporac):
    - [x] A mail server with the ability to send email (phish and attachments)
    - [x] A mail server with the ability to receive email (bounces, etc)
    - [x] Use both Thunderbird and Cobalt Strike to send email (via the mail server)
    - [x] Pass email checks (ie use DKIM) to reduce the chance of being identified as spam from the start
  - [x] PCA - Specific acceptance criteria (provided by @BenBreaksThings):
    - [x] Send email from a Teamserver (Cobalt Strike) instance
    - [x] View mail log to confirm that emails were successfully sent
      - Can be done via: `docker-compose logs postfix`
    - [x] Include the following commonly-used mail user accounts for the specified domain: `admin`, `contact`, `info`, `noreply`
  - [x] RTA - Does not use ServerSetup script (or mail servers) as part of default build (per @randaal)
- [x] Email can be sent from the assessment environment via:
  - [x] A Gophish instance
  - [x] A Teamserver (Cobalt Strike) instance

**Comment by felddy** [comment]
Only the mail server functionality of that script needs to be ported.  This work has already been completed with several containers that make up this composition: https://github.com/cisagov/pca-gophish-composition

**Comment by dav3r** [comment]
All work required for this issue has been completed.

@justinforbes and @kyleevers will spread the message that assessment operators should no longer use `ServerSetup.sh` in the COOL.  Thanks!
